In [3]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor

In [7]:
url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/airline-passengers.csv'
df = pd.read_csv(url, parse_dates=['Month'], index_col='Month')
df.head(10)

            Passengers
Month
1949-01-01         112
1949-02-01         118
1949-03-01         132
1949-04-01         129
1949-05-01         121
1949-06-01         135
1949-07-01         148
1949-08-01         148
1949-09-01         136
1949-10-01         119

In [5]:
def toXy(df, window_size = 3):
    n = df.shape[0] - window_size
    data = {}
    for i in range(window_size):
        data[f'x_{i}'] = df['Passengers'].values[i:n+i]
    data['y'] = df['Passengers'][window_size:]
    return pd.DataFrame(data)

In [6]:
toXy(df)

            x_0  x_1  x_2    y
Month
1949-04-01  112  118  132  129
1949-05-01  118  132  129  121
1949-06-01  132  129  121  135
1949-07-01  129  121  135  148
1949-08-01  121  135  148  148
...         ...  ...  ...  ...
1960-08-01  472  535  622  606
1960-09-01  535  622  606  508
1960-10-01  622  606  508  461
1960-11-01  606  508  461  390
1960-12-01  508  461  390  432

[141 rows x 4 columns]